# Generated by Django 2.2.4 on 2019-09-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('cast', models.ManyToManyField(related_name='acted', to='screenplay_generator.Person')),
                ('director', models.ManyToManyField(related_name='directed', to='screenplay_generator.Person')),
                ('genre', models.ManyToManyField(related_name='films', to='screenplay_generator.Genre')),
                ('writer', models.ManyToManyField(related_name='wrote', to='screenplay_generator.Person')),
            ],
        ),
    ]
